### ISSUE TITLE
Error during using predict endpoint

### ISSUE THREAD

**Issue by T-Zema** [Matuszx/Predykcja-pogody#1]
here is ss from the enpoint

![image](https://github.com/Matuszx/Predykcja-pogody/assets/40647700/87c5922d-8972-48af-85a2-77b4f299554e)

here is in code form error

```
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\src\server.py:15: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = data.fillna(method='ffill')  # Fill missing values using forward fill
 * Debugger is active!
 * Debugger PIN: 119-560-484
127.0.0.1 - - [26/Jun/2024 12:58:27] "GET /predict HTTP/1.1" 500 -
Traceback (most recent call last):
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\src\server.py", line 27, in predict
    next_day['Date'] = (datetime.datetime.strptime(last_day['Date'], '%Y-%m-%d') + datetime.timedelta(days=1)).strftime('%Y-%m-%d')  # Advance the date by one day
  File "C:\ProgramData\Anaconda3\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\ProgramData\Anaconda3\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '12/22/2010' does not match format '%Y-%m-%d'
127.0.0.1 - - [26/Jun/2024 12:59:04] "GET /predict HTTP/1.1" 500 -
Traceback (most recent call last):
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\Projekty\doktorat\Zajęcia\uslugi sieciowe i ml\projekty stud\Predykcja-pogody\src\server.py", line 27, in predict
    next_day['Date'] = (datetime.datetime.strptime(last_day['Date'], '%Y-%m-%d') + datetime.timedelta(days=1)).strftime('%Y-%m-%d')  # Advance the date by one day
  File "C:\ProgramData\Anaconda3\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\ProgramData\Anaconda3\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '12/22/2010' does not match format '%Y-%m-%d'
```

Perhaps i think where is the problem i manualy downloaded weatherAUS.csv from https://github.com/gchoi/Dataset/blob/master/weatherAUS.csv
Because file weatherAUS.csv in the project was empty

It is recommended that you put your working weatherAUS.csv When you are done with it please rememeber to update readme. Readme is holy grail to projects ;)

**Comment by Matuszx** [comment]
Thank you :) simple mistake, csv is updated
